CFLAGS=-O3 -std=c++11 -pg -D_DEBUG -g -c -Wall
all:
	g++ -std=c++0x -g -Wall -o hello main.cpp State.h Edge.h Graph.h Graph.cpp DFA_State.h DFA_State.cpp GrammerParser.h GrammerParser.cpp NFA_To_DFA.h NFA_To_DFA.cpp Lexical_Analyzer.h Lexical_Analyzer.cpp Minimization.h Minimization.cpp Tokens.h Tokens.cpp -o hello
